In [1]:
import pandas as pd

In [6]:
df = pd.read_excel('./input/RIBOSOME_mitochondria.xlsx')
df.index = df.id.to_list()

In [7]:
df_pro = pd.read_excel('./input/PROTEIN_stoich_curation_2021-09-28.xlsx')
df_pro.index = df_pro.id.to_list()

In [8]:
for i in df.index:
    if i not in ['rrna15s_m', 'rrna21s_m']:
        print(df_pro.loc[i, 'MW (g/mmol)'])

32.18766
45.7717
32.01693
32.93776
33.89172
25.47128
16.79055
29.90511
18.52629
22.04072
19.33188
16.20329
37.51102
27.34299
19.45429
18.17791
35.2905
30.33034
35.0653
42.2998
30.0407
36.31037
10.30704
20.27381
21.95294
8.33591
11.82571
11.06785
42.40241
17.18985
17.48199
16.50972
44.59851
32.34025
16.87217
30.16566
11.63097
12.2157
28.89806
22.54288
18.53438
15.80593
16.1523
27.20958
39.63582
44.64876
45.85753
56.89811
36.08094
14.75153
28.1066
18.37344
31.59228
23.10988
25.69357
16.11494
13.3047
32.09922
14.59954
27.67962
15.21934
19.55846
36.77716
52.37034
12.69521
36.99798
11.30795
15.01415
31.43022
36.09858
38.28403
40.91526
43.19421
57.31435

In [5]:
df_pro

,id,gene_src,name,uniprot,subloc_assigned,cofactor_stoich,cofactor_comments,MW (g/mmol),sequence,status
0,Q0045,Q0045,COX1,P00401,mm,"hemegen_c:2,cu2_c:1",Binds 2 heme A groups non-covalently per subun...,59.59198,MVQRWLYSTNAKDIAVLYFMLAIFSGMAGTAMSLIIRLELAAPGSQ...,cofAsgnManual
1,Q0080,Q0080,ATP8,P00856,mm,NaN,NaN,5.36422,MPQLVPFYFMNQLTYGFLLMITLLILFSQFFLPMILRLYVSRLFISKL*,NaN
2,Q0085,Q0085,ATP6,P00854,mm,NaN,NaN,28.12549,MFNLLNTYITSPLDQFEIRTLFGLQSSFIDLSCLNLTTFSLYTIIV...,NaN
3,Q0105,Q0105,COB,P00163,mm,hemegen_c:2,Binds 2 heme b groups non-covalently per subunit.,43.86371,MAFRKSNVYLSLVNSYIIDSPQPSSINYWWNMGSLLGLCLVIQIVT...,cofAsgnManual
4,Q0130,Q0130,OLI1,P61829,mm,NaN,NaN,8.27731,MQLVLAAKYIGAGISTIGLLGAGIGIAIVFAALINGVSRNPSIKDT...,NaN
...,...,...,...,...,...,...,...,...,...,...
1203,YDR347W,YDR347W,MRP1,P10662,m,NaN,NaN,36.09858,MLRFTGARAIRKYSTRYALEHLKEGAPLKGLFSIEGLQKAWFDRVK...,addedTranslationMachinery
1204,YGR084C,YGR084C,MRP13,P12686,m,NaN,NaN,38.28403,MGTITVVINEGPILLIRALHRATTNKKMFRSTVWRRFASTGEIAKA...,addedTranslationMachinery
1205,YGR165W,YGR165W,MRPS35,P53292,m,NaN,NaN,40.91526,MSYGLTGTSSKLRGTSSIFSWTQVRHFSRRRIAYPFYPFKKLGRQH...,addedTranslationMachinery
1206,YDR494W,YDR494W,RSM28,Q03430,m,NaN,NaN,43.19421,MRSSMFRCVSRAHYSTSVTEDFINSILARAQEATAKASSNALKLDK...,addedTranslationMachinery
1207,YDR036C,YDR036C,EHD3,P28817,m,NaN,NaN,57.31435,MLRNTLKCAQLSSKYGFKTTTRTFMTTQPQLNVTDAPPVLFTVQDT...,addedTranslationMachinery

In [3]:
df

           id      name alias factor_subunit  paralog  MW (g/mmol)
0   rrna15s_m  15S_RRNA   NaN            SSU      NaN          NaN
1   rrna21s_m  21S_RRNA   NaN            LSU      NaN          NaN
2     YDR116C     MRPL1  uL1m            LSU      NaN          NaN
3     YEL050C      RML2  uL2m            LSU      NaN          NaN
4     YGR220C     MRPL9  uL3m            LSU      NaN          NaN
..        ...       ...   ...            ...      ...          ...
71    YDR347W      MRP1  mS43            SSU      NaN          NaN
72    YGR084C     MRP13  mS44            SSU      NaN          NaN
73    YGR165W    MRPS35  mS45            SSU      NaN          NaN
74    YDR494W     RSM28  mS46            SSU      NaN          NaN
75    YDR036C      EHD3  mS47            SSU      NaN          NaN

[76 rows x 6 columns]